import Footer from "@/components/footer";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import Providers from "@/lib/providers/Provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme='light'
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </Providers>
        </body>
    </html>
  );
}
